export const financialTips = [
  { tip: "Track your monthly expenses to understand where your money goes." },
  { tip: "Always save at least 10% of your income before spending." },
  { tip: "Build an emergency fund worth 3–6 months of expenses." },
  { tip: "Avoid buying things on impulse; wait 24 hours before deciding." },
  { tip: "Pay off high-interest debt as early as possible." },
  { tip: "Invest early to take advantage of compound interest." },
  { tip: "Set clear financial goals for better money planning." },
  { tip: "Compare prices before making major purchases." },
  { tip: "Use credit cards responsibly and pay the full balance monthly." },
  { tip: "Automate your savings to stay consistent." },
  { tip: "Avoid taking unnecessary loans for non-essential items." },
  { tip: "Review your subscriptions and cancel what you don’t use." },
  { tip: "Track your credit score regularly." },
  { tip: "Create a monthly budget and stick to it." },
  { tip: "Invest in low-cost index funds for long-term growth." },
  { tip: "Don’t keep too much money idle in a savings account." },
  { tip: "Always have health insurance to avoid big medical expenses." },
  { tip: "Start a side income to diversify your earnings." },
  { tip: "Avoid emotional investing; follow a strategy." },
  { tip: "Never invest in something you don’t understand." },
  { tip: "Increase your savings rate every time your income increases." },
  { tip: "Check for cashback or rewards before shopping online." },
  { tip: "Buy used items where quality doesn’t matter much." },
  { tip: "Track your net worth at least once every quarter." },
  { tip: "Set aside money for yearly expenses instead of last-minute crunch." },
  { tip: "Keep a separate account for emergency savings." },
  { tip: "Revisit your financial goals every six months." },
  { tip: "Do not co-sign loans unless you’re ready to pay it yourself." },
  { tip: "Look for cheaper insurance premiums by comparing providers." },
  { tip: "Don’t chase unrealistic returns; aim for steady growth." },
  { tip: "Sell unused items to generate extra income." },
  { tip: "Cut down on eating out if you’re trying to save more." },
  { tip: "Avoid lifestyle inflation as your income grows." },
  { tip: "Review your bank statements for hidden charges." },
  { tip: "Use budgeting apps to simplify tracking expenses." },
  { tip: "Split big goals into smaller monthly targets." },
  { tip: "Learn basic personal finance to make better decisions." },
  { tip: "Save for retirement even if you’re young." },
  { tip: "Avoid withdrawing from your retirement savings early." },
  { tip: "Keep your financial documents organized in one place." },
  { tip: "Choose long-term investing over trading for stability." },
  { tip: "Buy term insurance, not expensive investment-linked plans." },
  { tip: "Build good financial habits instead of relying on discipline." },
  { tip: "Focus on increasing income, not just cutting expenses." },
  { tip: "Don’t finance depreciating assets unless necessary." },
  { tip: "Plan your taxes to avoid last-minute pressure." },
  { tip: "Review your insurance coverage yearly." },
  { tip: "Negotiate your salary; it compounds over your career." },
  { tip: "Avoid holding too many credit cards." },
  { tip: "Keep some savings in liquid assets for emergencies." },
  { tip: "Do a no-spend week every few months to reset your habits." },
  { tip: "Save for big purchases instead of using EMI for everything." },
  { tip: "Build long-term wealth through consistent investing." }
];
